//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverGreenWebApi.DBHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qsr_androidEntities : DbContext
    {
        public qsr_androidEntities()
            : base("name=qsr_androidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<feedbackmaster> feedbackmasters { get; set; }
        public virtual DbSet<loginmaster> loginmasters { get; set; }
        public virtual DbSet<promocodemaster> promocodemasters { get; set; }
    }
}
